
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 11 12:49:25 CST 2015
//----------------------------------------------------

package olc1_proyecto1;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int abrircorchetes = 6;
  public static final int comilla = 38;
  public static final int distinto = 47;
  public static final int saltolinea = 21;
  public static final int resta = 55;
  public static final int suma = 54;
  public static final int cerrarfila = 25;
  public static final int cerrarcuerpo = 16;
  public static final int cerrarcorchetes = 7;
  public static final int multiplicacion = 56;
  public static final int cerrartabla = 23;
  public static final int abrirespacio = 17;
  public static final int inicio = 9;
  public static final int mayorque = 44;
  public static final int urlw = 31;
  public static final int definicionvariable = 33;
  public static final int cerrartitulo = 8;
  public static final int si = 50;
  public static final int cerrarespacio = 18;
  public static final int abrirtabla = 22;
  public static final int abrircuerpo = 15;
  public static final int numero = 53;
  public static final int iniciophp = 2;
  public static final int urll = 32;
  public static final int cerrarparentesis = 5;
  public static final int EOF = 0;
  public static final int verdadero = 39;
  public static final int abrirparentesis = 4;
  public static final int error = 1;
  public static final int cerraratitulo = 14;
  public static final int abrirtitulo = 13;
  public static final int cerrarcabecera = 12;
  public static final int menorigual = 45;
  public static final int abrircabecera = 11;
  public static final int punto = 36;
  public static final int idVariable = 52;
  public static final int menorque = 43;
  public static final int abrirparrafo = 19;
  public static final int cerrarcolumnacabecera = 27;
  public static final int abrircolumnacabecera = 26;
  public static final int id = 30;
  public static final int falso = 40;
  public static final int y = 48;
  public static final int abrirfila = 24;
  public static final int mayorigual = 46;
  public static final int fin = 10;
  public static final int cerrarcorchete = 42;
  public static final int cerrarparrafo = 20;
  public static final int abrircorchete = 41;
  public static final int o = 49;
  public static final int puntocoma = 37;
  public static final int abrircolumna = 28;
  public static final int echo = 34;
  public static final int division = 57;
  public static final int asignacion = 35;
  public static final int finphp = 3;
  public static final int sino = 51;
  public static final int cerrarcolumna = 29;
}

